### ISSUE TITLE
Documentation examples – in topics and new topic dedicated to the CLI 

### ISSUE THREAD

**Issue by bazal4o** [IgniteUI/igniteui-cli#108]
As part of documentation updates we need to update the Wiki of the CLI, existing general topics, overview/adding topics related to the components supported in the CLI and create new topics related to the CLI

- [x] Create cli repo wiki #109 
- [x] Update existing ignite ui general topics with cli content #110
- [x] Update overview/adding topics related to the components #111
- [x] Create new topic related to the CLI into ignite ui help #112
