### ISSUE TITLE
Extensibility support

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/igniteui-cli#70]
We already have some of the infrastructure in place to load [`Template`](https://github.com/IgniteUI/ignite-ui-cli/blob/master/lib/types/Template.d.ts)-s, so
- [ ] Expose required interfaces, potentially some of the utils/base types #190 
      - [ ] Util refactor and export 
      - [ ] Implement extension points
- [x] Define expected format extenders need to provide
- [ ] Dependecies 
      Support npm dependencies #192 
      React projects/templates load module dependencies instead of core/lob #193 
      Angular-wrappers projects/templates load module dependencies instead of core/lob #194 
      jQuery projects/templates load module dependencies instead of core/lob #195 
     Support Custom dependencies #196
     Provide more detailed `dependencies` format for Ignite UI for Angular project #200 

- [ ] Versioning of templates and projects - how to deal with updates #189
- [ ] Project template extensibility #188 
  - Provide extension point on level project (next to empty project templates)
  - Implement id parameter for new project call 
- [ ] Custom templates as npm package? #191 

Questions:
- So far I believe we've settled to only have templates that add to existing components. Should extensions be able defined their own components, groups and maybe even further?
- There are multiple options we can go about this - load packages either based on auto-discovery via keywords/naming or via additional command to add them in local/global config (related #67). Could also be simple file structure if we use the config.
