### ISSUE TITLE
Multi-package support for Ignite UI for Angular

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/igniteui-cli#720]
### Description  
Adjust related schematics and templates to handle package from alternative feed as well as the current from the npm registry.

- [x] Update config schematic (part of main lib add workflow) #721
- [x] Update igx templates to use the package as variable #722
- [x] Create and upgrade package schematic #723
- [x] Add a command `ig upgrade-packages` to trigger the package change #727
- [x] Add a question to Step by Step mode to change package #724 
- [x] Add support for dock manager #741 
- [Optional] Update config schematic (part of main lib add workflow) to detect and trigger package change #725
